ack.acronym=hp
ack.title=Harry Potter and the Philosopher's Stone
ack.author.last.name=Rowling
ack.author.first.name=J.K.
ack.publisher=Bloomsbury
ack.publication.date=2004
ack.originally=1997
ack.research.assistant.team=Kyra Hetherington (with a little help from Abby Phillips and Avery McAllister through Uvic's HUMA 180 Internship)
ack.notes=All dates have been based on the 1990/91 calendar due to textual evidence suggesting that Harry Potter’s birthday takes place on Tuesday  July 31. Most fan communities and textual evidence from later books points to events taking place in 1990/92.
