ack.acronym=gs
ack.title=A Visit from the Goon Squad
ack.author.last.name=Egan
ack.author.first.name=Jennifer
ack.publisher=Random House
ack.publication.date=2011
ack.originally=
ack.research.assistant.team=Kyra Hetherington and Rowan Watts
ack.notes=
