ack.acronym=pp
ack.title=Pride and Prejudice
ack.author.last.name=Austen
ack.author.first.name=Jane
ack.publisher=Penguin Classics
ack.publication.date=2002
ack.originally=1813
ack.research.assistant.team=Emma Ainsworth, Leia Soulsbury, and Rowan Watts
ack.notes=
