ack.acronym=de
ack.title=Disappearing Earth
ack.author.last.name=Phillips
ack.author.first.name=Julia
ack.publisher=Vintage Books
ack.publication.date=2019
ack.originally=
ack.research.assistant.team=Jessica Jay and Faith Lapointe
ack.notes=
