ack.acronym=tsatf
ack.title=The Sound and the Fury
ack.author.last.name=Faulkner
ack.author.first.name=William
ack.publisher=Vintage International
ack.publication.date=2005
ack.originally=1929
ack.research.assistant.team=Emma Ainsworth and Rowan Watts
ack.notes=We referenced Stephen M. Ross and Noel Polk's Reading Faulkner: The Sound and the Fury / Glossary and Commentary. University Press of Mississippi  1996.
