ack.acronym=toc
ack.title=Tropic of Orange
ack.author.last.name=Yamashita
ack.author.first.name=Karen Tei
ack.publisher=Coffee House Press
ack.publication.date=1997
ack.originally=
ack.research.assistant.team=Kyra Hetherington and Alexander McLachlan
ack.notes=
